baseURL = 'https://blog.hath.top/'
title = '拾遗录'
theme = ["github.com/D-Sketon/hugo-theme-reimu"]
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'

[languages]
[languages.zh-CN]
languageName = '简体中文'
weight = 1
hasCJKLanguage = true

[markup.highlight]
guessSyntax = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
