name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@master

      - name: install node
        uses: actions/setup-node@v2.1.5

      - name: yarn install and build
        run: |
          yarn install
          yarn build
        env:
          CI: true

      - name: push to nas
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}

  wechat:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@master

      - id: files
        uses: jitterbit/get-changed-files@v1

      - run: |
          for changed_file in ${{ steps.files.outputs.added }}
            do
              extension=${changed_file##*.}
              echo $extension
              if  [ $extension = 'md' ]
                then
                  curl ${{ secrets.WECHAT_SERVER_URL }} -X POST -F "file=@${changed_file}" -H "Authorization: ${{ secrets.WECHAT_SERVER_TOKEN }}"
              fi
            done
