name: 测试
on:
  push:
    branches:
      - workflow
jobs:
  wechat:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@master

      - id: files
        uses: jitterbit/get-changed-files@v1

      - run: |
          apt update
          apt install curl
          for changed_file in ${{ steps.files.outputs.added }}
            do
              extension=${changed_file##*.}
              echo $extension
              if  [ $extension = 'md' ]
                then
                  curl ${{ secrets.WECHAT_SERVER_URL }} -X POST -F "file=@${changed_file}" -H "Authorization: ${{ secrets.WECHAT_SERVER_TOKEN }}"
              fi
            done
